#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://192.168.1.118:1433;DatabaseName=activiti-test
#spring.datasource.username=sa
#spring.datasource.password=sa@12345
#spring.activiti.check-process-definitions=false
#server.port=8080
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.1.118:1433;DatabaseName=activiti-test
    username: sa
    password: sa@12345
    druid:
      max-active: 20
      min-idle: 1
      max-wait: 60000
  thymeleaf:
    cache: false
mybatis:
  check-config-location: false
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springactiviti.model